packages:
  - 'apps/*'
  - 'packages/*'

nodeLinker: hoisted
shamefullyHoist: true
strictDepBuilds: false

allowBuilds:
  '@nestjs/core': true
  '@swc/core': true
  bcrypt: true
  cpu-features: set this to true or false
  esbuild: true
  msgpackr-extract: true
  ssh2: set this to true or false
