packages:
  - 'apps/*'
  - 'packages/*'

nodeLinker: hoisted
shamefullyHoist: true
strictDepBuilds: false

allowBuilds:
  '@nestjs/core': true
  '@swc/core': true
  bcrypt: true
  esbuild: true
  msgpackr-extract: true
